"""The typed playbook bodies (R-audit-14, `dd72855` finding 1): the ONE source.

Each tuple below is a reviewed playbook section as ordered typed blocks. `render_body`
turns it into the exact bytes `docs/DEPLOYMENT.md` must publish under the matching
heading, and the assembled OPS.CUTOVER.PROCEDURES verifier holds the document to that
render — so the document is a projection, not an authoring lane, and the operator lane
is emitted only from typed `Command` records.

Every byte of every block joins the complete-definition pin, so ANY edit here is the one
deliberate re-pin a reviewer signs off. That is where a prose instruction like "Delete
all backups." is refused: not by classifying English, which no machinery can do
reliably, but by a human reading the diff that the pin forces into review.
"""

from docs.contracts.body import Narrative, OperatorInstruction
from docs.contracts.playbook import Command

PR5B_BODY = (
    Narrative(
        "## 9. PR 5b cutover — brief full maintenance window\n"
        "\n"
        "PR 5b adds the reviewer-actor trust floor that closes the \"review completed /\n"
        "approved by anyone holding the shared secret\" forgery: it requires the signed\n"
        "envelope's `actor` to identify the reviewer (`docs/PLATFORM_INTEGRATION.md`\n"
        "§3), not just the payload. **This is not a rolling deploy.** During any\n"
        "old/new overlap, an old replica still honors the exact forgery this release\n"
        "closes — an old API applies `reviewer.manual_approve` inline with no actor\n"
        "floor, and an old pipeline worker (which claims a job purely by kind, with no\n"
        "event-type filter) can still close a queued `system`-actor website completion\n"
        "under the old actorless semantics. There is no way to keep an old replica\n"
        "serving *any* traffic while guaranteeing it never touches a sensitive event,\n"
        "so this release ships as a **brief full maintenance window** — the same\n"
        "non-hot **stop → deploy → start** pattern PR 5a used (§2), extended to workers\n"
        "as well as the API, which removes old/new overlap entirely. No migration\n"
        "ships with this change.\n"
        "\n"
        "The window is a real interruption, not a seamless roll: `POST\n"
        "/v1/cases/{case_id}/events` is unavailable for its duration, for every event\n"
        "type, and the pipeline is stopped. The \"no loss\" guarantee for that\n"
        "interruption is a **platform prerequisite**, not something the current API\n"
        "contract provides on its own — today the contract only directs retry on a\n"
        "*network failure* (`docs/PLATFORM_INTEGRATION.md` §3), but a load balancer\n"
        "with every API target down instead returns 502/503/504, and a delayed retry\n"
        "that reuses the original signature can blow the 300-second HMAC skew. Before\n"
        "scheduling the window, confirm with the platform team that they will\n"
        "pause/buffer **all** event submission for its duration and drain it\n"
        "afterward — re-signing each retried body with a **fresh timestamp/signature**\n"
        "against the **same idempotency key** — or, if they prefer to keep sending,\n"
        "that they treat 502/503/504 the same as a transport failure: retryable with\n"
        "the same body/key and a fresh signature.\n"
        "\n"
        "Steps:\n"
        "\n"
        "0. **Before the window:** build and publish the reviewed image; record its\n"
        "   **digest**. Every step below that runs code — the recovery one-shot, the\n"
        "   new API, the new workers — is pinned to that one digest. The recovery\n"
        "   module (`kyc_tool.ops.requeue_interrupted_jobs`) exists only in the new\n"
        "   image, so running it on the still-current old task definition fails with\n"
        "   `No module named …`.\n"
        "1. **Pause all platform event submission** (every event type, not only the\n"
        "   two sensitive ones) and block the ops composer: the platform buffers\n"
        "   outbound events, and the composer route (a `POST` to `/ui/api/send-event`) is\n"
        "   edge-blocked — or old replicas are flipped to `KYC_UI_ENABLED=false` — so\n"
        "   an operator on a still-live old replica can't post an inline forged\n"
        "   approval. The whole window is a maintenance pause; a partial pause cannot\n"
        "   guarantee no-loss.\n"
        "2. **Stop all old processes together** — the API pool and the pipeline-worker\n"
        "   pool, as one coordinated action, **no graceful drain**, without awaiting\n"
        "   either pool before signaling the other. Confirm both pools are at **zero**\n"
        "   before continuing. A sequenced stop leaves the not-yet-stopped pool live\n"
        "   and able to commit a forgery in the gap; the edge block cannot revoke a\n"
        "   request already inside an old API's threadpool, so old APIs must be\n"
        "   *stopped*, not drained. Hard termination is safe here: every transition\n"
        "   (and every ingest) commits in one transaction, so interrupted work simply\n"
        "   rolls back.\n"
        "3. **Recover interrupted jobs.** With both pools confirmed at zero, run\n"
        "   ``python -m kyc_tool.ops.requeue_interrupted_jobs`` as a one-shot task\n"
        "   **pinned to the §0 digest**, before any new worker starts. With every\n"
        "   worker stopped and none yet restarted, every `status='running'` job row is\n"
        "   by definition interrupted — regardless of lease expiry, and with no need\n"
        "   for a worker-liveness registry. The command requeues that whole set\n"
        "   transactionally **without** consuming the forced-stop attempt (this is an\n"
        "   operator-initiated interruption, not a handler failure — consuming the\n"
        "   attempt could let the passive reaper dead-letter an expired final-attempt\n"
        "   job before it ever reaches the new actor guard), and it asserts zero\n"
        "   `running` rows remain on completion. It must not run while any worker is\n"
        "   live — confirming both pools at zero (step 2) is its precondition.\n"
        "4. **Deploy the new API and worker services, both pinned to the §0 digest**\n"
        "   (attest it). Bring the **API** up first and hold **workers at zero** until\n"
        "   step 5 passes — workers serve no HTTP, so the API probes below cannot\n"
        "   vouch for a stale or mismatched worker image, and starting workers early\n"
        "   would let one honor a recovered pre-upgrade completion.\n"
        "5. **Direct-probe each new API replica** on a trusted path that bypasses the\n"
        "   edge rule (internal target-group address or port-forward) — probing\n"
        "   through the edge would let the load balancer's own 403 falsely certify a\n"
        "   broken app. Use only side-effect-free probes (each is rejected at the\n"
        "   ingest floor and rolls back, writing no rows) and assert the response\n"
        "   **body**, not just the status code:\n"
        "   - a signed `system`-actor `website.review_completed` against a valid open\n"
        "     task → the app's **422** (a 404/409 would mask a broken actor floor);\n"
        "   - a mismatched-actor `reviewer.manual_approve` → the app's **422**;\n"
        "   - the composer → the app's **403** for both sensitive event types.\n"
        "\n"
        "   Do not probe the decide-txn guard's live behavior in production this way —\n"
        "   a real pipeline run there writes a decision and enqueues a callback\n"
        "   unconditionally, and the outbox publisher (a separate process, not stopped\n"
        "   in step 2) would deliver it to the platform. That behavior is proven\n"
        "   **before the window, in staging**, against the exact §0 digest; attest the\n"
        "   same digest here.\n"
        "6. **Start the new workers** (they now claim the recovered queue under the\n"
        "   new decide-txn actor guard), then **resume** — unpause platform event\n"
        "   submission and unblock the composer route.\n"
        "\n"
        "### Rollback\n"
        "\n"
        "Rollback mirrors the same window and pins the recovery one-shot to the **last\n"
        "image that still contains it**: pause all submission, stop all new processes\n"
        "together (same coordinated hard stop; same recovery command, run against a\n"
        "digest that has the module), redeploy the prior image for API **and**\n"
        "workers, verify, start workers, resume — accepting that the prior image\n"
        "restores pre-PR-5b behavior.\n"
        "\n"
        "**Rollback verification is non-mutating only:** `GET` probes of `/readyz`\n"
        "and `/healthz`, and prior-image digest attestation. Do **not** run the step-5\n"
        "sensitive-mutation probes against the prior image — that image is the current\n"
        "vulnerable code with no actor floor, so a mismatched-actor `manual_approve`\n"
        "probe would actually `approve` the case inline, and a `system`-actor\n"
        "completion probe would queue a run the restored old worker can honor: the\n"
        "probe would *perform* the forgery it is meant to detect, not find it.\n"
        "Exercise that behavior only in staging or an isolated DB. Keep all submission\n"
        "and the composer blocked until the safe, non-mutating checks pass.\n"
        "",
        commands=(
            Command(('python', '-m', 'kyc_tool.ops.requeue_interrupted_jobs')),
        ),
    ),
)


BUNDLE_PINNING_BODY = (
    Narrative(
        "## 10. PR 6 cutover — bundle-pinning activation\n"
        "\n"
        "PR 6 pins the policy bundle (and records the engine build) a run is actually\n"
        "scored and decided under, instead of trusting whatever the worker process\n"
        "happened to have loaded. It ships in two parts: a **rolling** part (safe to\n"
        "deploy like any other release) and a **drained** part (the flag flip, not\n"
        "safe to roll).\n"
        "\n"
        "**Rolling — migration + provenance, flag stays off.** Migration 011\n"
        "(`policy_bundles`, `bundle_pinning_epoch`, and the new nullable provenance\n"
        "columns) is additive and hot-compatible — deploy it through the normal §4\n"
        "flow. It is hot-compatible precisely because its three provenance-column\n"
        "CHECKs land `NOT VALID` (a brief, metadata-only lock, no table scan) and are\n"
        "validated by the follow-on migration 012 via `VALIDATE CONSTRAINT` under a\n"
        "non-blocking lock, so the rolling `alembic` upgrade-to-head (the §4 one-shot) does not stall\n"
        "ingest/decide writers on large `checks`/`decisions` audit tables. On the PR6\n"
        "image, the API and pipeline worker seed and read back the\n"
        "on-disk policy bundle at startup (failing closed on a corrupt persisted row)\n"
        "and every automatic/manual decision starts recording bundle **and** engine\n"
        "provenance immediately — `Settings.enforce_bundle_pinning`\n"
        "(`KYC_ENFORCE_BUNDLE_PINNING`) stays `false`, so scoring itself is\n"
        "byte-identical to pre-PR6 (a strict no-op; see ADR-005). A `GET` on `/readyz`\n"
        "unconditionally confirms the process's loaded bundle is durably resolvable\n"
        "from the store — watch it like any other readiness check during this\n"
        "rollout.\n"
        "\n"
        "**Seed the bundle.** Before relying on the store for anything beyond a\n"
        "process's own startup seeding (in particular, before the preflight below),\n"
        "confirm the release's bundle is in `policy_bundles`:\n"
        ""
    ),
    OperatorInstruction(commands=(
        Command(('python', '-m', 'kyc_tool.ops.seed_policy_bundle', '--expect-hash', '<sha256>')),
    )),
    Narrative(
        "\n"
        "`--expect-hash` is the hash an operator names from a reviewed source (the\n"
        "release notes / deploy manifest) — the command computes the hash of the\n"
        "bundle at `KYC_POLICY_DIR`, compares it to `--expect-hash`, and **only on a\n"
        "match** stores it; a mismatch raises and writes nothing, so a wrong policy\n"
        "directory can never land a row silently.\n"
        "\n"
        "**Drained cutover — flip the flag.** This is not a rolling deploy: every\n"
        "worker that claims a `run_transition` job while `enforce_bundle_pinning` is\n"
        "inconsistent across the pool risks resolving a bundle differently from its\n"
        "peers. Flip it with the pool fully drained, the same shape PR 5a/5b used:\n"
        "\n"
        "1. **Preflight.** ``python -m kyc_tool.ops.verify_pinnable_backlog`` — checks\n"
        "   that every queued/running/dead `run_transition` job's run has a\n"
        "   creation-pin bundle that actually loads from the store. **A nonzero exit\n"
        "   blocks the cutover** — seed the missing bundle(s) (§ above, or historical\n"
        "   recovery via the same command with the older policy directory) and re-run\n"
        "   until it exits 0.\n"
        "2. **Disable autoscaling/restarts; confirm zero old workers.** At the\n"
        "   orchestrator (not by row count — a job-table count doesn't prove process\n"
        "   quiescence), confirm every pipeline-worker replica currently running\n"
        "   predates this cutover is gone.\n"
        "3. **Recover interrupted jobs.** With workers confirmed at zero, run\n"
        "   ``python -m kyc_tool.ops.requeue_interrupted_jobs`` once — every\n"
        "   `status='running'` job at this point is by definition interrupted; it\n"
        "   requeues the whole set without consuming the forced-stop attempt and\n"
        "   asserts zero `running` rows remain. Its precondition is \"all workers\n"
        "   confirmed stopped\" (step 2) — do not run it while any worker is live.\n"
        "4. **Start flag-on workers.** Set `KYC_ENFORCE_BUNDLE_PINNING=true` and start\n"
        "   the pipeline-worker pool. Confirm the startup **attestation** log line on\n"
        "   every replica — a structured `bundle_pinning_ready` event carrying\n"
        "   `flag=true`, `bundle_hash`, and `engine_build_id` — emitted only after the\n"
        "   worker's own seed-and-verify passes, so a replica that never logs it never\n"
        "   started claiming jobs.\n"
        "5. **Resume.** Unpause whatever was paused for the drain (the API itself\n"
        "   never stopped — only the worker pool is drained here).\n"
        "\n"
        "**Activate the epoch.** Once the cutover is verified stable, write the\n"
        "durable activation record:\n"
        "",
        commands=(
            Command(('python', '-m', 'kyc_tool.ops.verify_pinnable_backlog')),
            Command(('python', '-m', 'kyc_tool.ops.requeue_interrupted_jobs')),
        ),
    ),
    OperatorInstruction(
        commands=(
        Command((
            'python', '-m', 'kyc_tool.ops.activate_bundle_pinning_epoch', '--expect-bundle-hash', '<sha256>',
            '--expect-engine', 'eng-1',
        )),
        ),
        wraps=(
            (
                'python -m kyc_tool.ops.activate_bundle_pinning_epoch \\',
                '    --expect-bundle-hash <sha256> --expect-engine eng-1',
            ),
        ),
    ),
    Narrative(
        "\n"
        "This compares the **locally loaded** policy bundle and this process's\n"
        "`ENGINE_BUILD_ID` against the `--expect-*` arguments before touching the\n"
        "database at all (a valid-but-wrong bundle is refused here, not merely by\n"
        "store-absence later), writes the singleton `bundle_pinning_epoch` row with\n"
        "database time, and read-back-fails if a concurrent activation already wrote\n"
        "different values — so a skewed operator clock or a mismatched second\n"
        "activation can never silently move the boundary. From `activated_at`\n"
        "onward, `docs/RUNBOOK.md`'s post-epoch alert treats any check/decision\n"
        "missing its provenance stamp as an anomaly, not an expected state.\n"
        "\n"
        "**Rollback — flag-only, no data migration.** Normal rollback for PR 6 never\n"
        "means resuming on a pre-PR6 image (that would silently stop writing\n"
        "provenance and, after the epoch, mint permanent NULLs — a defect, not a\n"
        "safe fallback). It means disabling the flag **on the PR6 image**, via the\n"
        "same drained shape: stop the worker pool → confirm zero running →\n"
        "`ops.requeue_interrupted_jobs` → start workers with\n"
        "`KYC_ENFORCE_BUNDLE_PINNING=false` → resume. The creation pin and\n"
        "provenance writing are preserved throughout; scoring simply returns to the\n"
        "process-loaded bundle. Migration 011 is **retained** — never downgrade it\n"
        "once any bundle row, provenance column, or the epoch row is populated (its\n"
        "downgrade deliberately refuses, the same forward-only-after-use contract\n"
        "migration 010 established in ADR-003).\n"
        ""
    ),
)


PR7B_CORE_BODY = (
    Narrative(
        "## 11. PR 7b-core cutover — drained maintenance window (migration 013)\n"
        "\n"
        "**Step 0 — pre-window diagnostic (BEFORE any outage):**\n"
        "0.1 Suspend the retention schedule.\n"
        "0.2 Terminate and wait for every active retention task.\n"
        "0.3 Capture target-orchestrator zero-running evidence. `TODO(integration)`: the exact\n"
        "    zero-running listing — the `aws` CLI's `ecs list-tasks` scoped to the cluster and the\n"
        "    retention family (or the EC2 equivalent) — and its expected zero-task output MUST be\n"
        "    recorded here as a typed operator command once the production substrate is chosen. A\n"
        "    pytest does NOT prove this — it is a deployment acceptance. Do not invent a substrate.\n"
        "0.4 With the schedule still suspended, run the digest-pinned\n"
        "    ``python -m kyc_tool.ops.verify_pr7b_core_backfill``. The result is valid ONLY while retention s"
        "tays\n"
        "    suspended AND the 0.3 attestation holds.\n"
        "0.5 On failure, ABORT here — before stopping service (no outage begun). Recovery is restore-or-block"
        ":\n"
        "    restore from authoritative backup the EXACT callback row, OR remain on 012 in\n"
        "    `BLOCKED_NO_AUTHORITATIVE_MAPPING`. Backup availability is an operator prerequisite. Activation "
        "(`024`) is\n"
        "    downstream and cannot repair this. Never fabricate a callback, delete a decision, or fall back t"
        "o\n"
        "    `decided_at`. On EVERY abort path, explicitly re-enable OR deliberately keep-frozen retention.\n"
        "    THE RESTORE PATH IS A SHIPPED CLI, reachable from HERE — a pre-window maintenance stop, not the"
        "\n"
        "    cutover (which 0.4 still gates): FIRST run the prerequisites check (read-only, takes NO\n"
        "    lock) and confirm it is GREEN — exact schema phase, correct role, `outbox_id_seq`\n"
        "    ownership, and timeout budgets:\n"
        "",
        commands=(
            Command(('python', '-m', 'kyc_tool.ops.verify_pr7b_core_backfill')),
        ),
    ),
    OperatorInstruction(commands=(
        Command(('python', '-m', 'kyc_tool.ops.verify_pr7b_ops_prerequisites', '--expect-revision', '012')),
    )),
    Narrative(
        "\n"
        "    A wrong maintenance credential OR wrong phase is caught HERE, not at `ALTER SEQUENCE`\n"
        "    inside the stop; then pause submissions,\n"
        "    hard-stop and attest EVERY writer (API,\n"
        "    pipeline, outbox, `dev_worker`, retention), then run\n"
        "    the restore CLI (dry-run first; add `--apply` to perform):\n"
        ""
    ),
    OperatorInstruction(
        commands=(
        Command((
            'python', '-m', 'kyc_tool.ops.restore_pr7b_core_callback', '--evidence', '<file.json>',
            '--expect-original-id', '<id>', '--expect-manifest-digest', '<sha256>',
        )),
        ),
        wraps=(
            (
                'python -m kyc_tool.ops.restore_pr7b_core_callback --evidence <file.json> \\',
                '    --expect-original-id <id> --expect-manifest-digest <sha256>',
            ),
        ),
    ),
    Narrative(
        "\n"
        "    `--expect-manifest-digest` is MANDATORY and is an INTEGRITY check: the tool recomputes\n"
        "    the sha256 of the evidence file (``sha256sum <file.json>``) and refuses unless it matches, so a"
        "\n"
        "    tampered or wrong file is rejected before any DB work — the file cannot self-certify by carrying"
        "\n"
        "    its own digest. The tool does NOT verify a cryptographic signature; the digest's authenticity is"
        "\n"
        "    yours to establish out of band, from a trusted/signed backup manifest (machine-verified signing"
        "\n"
        "    is a future option).\n"
        "    It validates the whole\n"
        "    contract below, inserts the exact original row, floors the sequence past the restored id\n"
        "    (`GREATEST(max(id), original_id) + 1`) in the SAME transaction, and fail-closed read-backs both"
        "\n"
        "    the acceptance predicate and the sequence before committing — any mismatch rolls back row and\n"
        "    sequence together. Then rerun 0.4 (the gate that reopens cutover) and either RESUME service or\n"
        "    proceed to the window. Pasting the SQL below by hand is NOT a sanctioned path — the earlier\n"
        "    revision of this section prescribed exactly that and was circular: the diagnostic stayed red\n"
        "    until the restore, while the sequence repair was documented as reachable only after cutover\n"
        "    step 2 and knew nothing of the id being restored (re-audit `f495de8` F1).\n"
        "0.6 RESTORE ACCEPTANCE CONTRACT (the restore in 0.5 is an executable identity requirement, not\n"
        "    advice — the backfill ranks by `outbox.id`, so a wrong id silently reverses the legacy order):\n"
        "    (a) BEFORE restoring, record from the backup the authoritative evidence tuple per missing\n"
        "        callback: `decision_id` plus **every schema-012 `outbox` column** —\n"
        "        `(id, kind, case_id, run_id, payload_json, status, attempts, next_attempt_at,\n"
        "        delivered_at, last_error, created_at)` — with `body_digest` computed ON THE BACKUP ROW as\n"
        "        `encode(sha256(convert_to(payload_json::text,'UTF8')),'hex')`. `md5(...)` is prohibited.\n"
        "        This procedure runs BEFORE 013, so it must name NO 013-only column: `resolved_at`,\n"
        "        `ordering_stream`, `decision_sequence` and the claim tuple do not exist yet. Omitting the\n"
        "        retry/audit columns is what makes \"exact\" false — a previously retried callback restored\n"
        "        with a reset `attempts`/`next_attempt_at`/`last_error` is NOT the row that was pruned.\n"
        "    (b) The restore MUST re-insert the ORIGINAL primary key AND every other recorded column:\n"
        "        `INSERT INTO outbox (id, kind, case_id, run_id, payload_json, status, attempts,\n"
        "         next_attempt_at, delivered_at, last_error, created_at) VALUES (<original_outbox_id>, ...)`"
        "\n"
        "         — every value from the evidence tuple, none defaulted. A\n"
        "        default-id INSERT is prohibited (it allocates a fresh id and re-ranks the restored older\n"
        "        callback as newer), and substituting `now()` for `delivered_at` is prohibited (it falsifies"
        "\n"
        "        the audit record). If the original id is unavailable, do NOT restore: remain\n"
        "        `BLOCKED_NO_AUTHORITATIVE_MAPPING` on 012. The evidence tuple is captured into the JSON\n"
        "        file the restore CLI's `--evidence` input consumes; `--expect-original-id` must repeat\n"
        "        the id (double entry). The id, body digest and decision linkage are machine-refused on\n"
        "        mismatch; the lifecycle fields are ATTESTED inputs from the backup — but the MANDATORY\n"
        "        `--expect-manifest-digest` (sha256 of the whole evidence file, from the signed manifest)\n"
        "        binds every one of them, so a falsified backup value cannot pass without also breaking the\n"
        "        signed digest. The signed manifest and the documented capture query are the sanctioned sourc"
        "e.\n"
        "    (c) ACCEPTANCE PREDICATE — POSITIVE and fail-closed. Run per restored callback; it MUST return\n"
        "        EXACTLY ONE row before proceeding. ZERO rows = still blocked. Do NOT invert it into a\n"
        "        \"select the mismatches, expect zero rows\" form: an absent row (or one restored under the\n"
        "        wrong `run_id`) matches nothing and would read as accepted.\n"
        "        `SELECT 1 AS accepted FROM outbox o JOIN decisions d ON d.id = :decision_id\n"
        "         WHERE o.id = :original_outbox_id AND o.kind = :original_kind\n"
        "           AND o.case_id = :case_id AND o.run_id = :run_id\n"
        "           AND d.case_id = o.case_id AND d.run_id = o.run_id\n"
        "           AND encode(sha256(convert_to(o.payload_json::text,'UTF8')),'hex') = :body_digest\n"
        "           AND o.status = :original_status\n"
        "           AND o.delivered_at IS NOT DISTINCT FROM :original_delivered_at\n"
        "           AND o.attempts = :original_attempts\n"
        "           AND o.next_attempt_at IS NOT DISTINCT FROM :original_next_attempt_at\n"
        "           AND o.last_error IS NOT DISTINCT FROM :original_last_error\n"
        "           AND o.created_at IS NOT DISTINCT FROM :original_created_at;`\n"
        "        Every schema-012 column is compared, so dropping any one of them from the restore fails\n"
        "        the predicate. `IS NOT DISTINCT FROM` is used for nullables so NULL matches NULL.\n"
        "    (d) THE SEQUENCE IS THE RESTORE CLI'S JOB — there is NO separate precondition to satisfy\n"
        "        first (re-audit `8377440` F3: the old text made the restore reachable only after a\n"
        "        `next_id > original_outbox_id` check that the documented `max=5`/`missing-id=100` case fails"
        ",\n"
        "        which is exactly the case the restore exists for). `restore_pr7b_core_callback` floors the\n"
        "        sequence to `GREATEST(max(id), original_id) + 1` in the SAME transaction as the row\n"
        "        insert, under `ACCESS EXCLUSIVE`, with a fail-closed read-back — whether the missing id is\n"
        "        below OR above the current high-water. It never `setval`s (a read-modify-write on a\n"
        "        non-transactional object that can rewind under concurrent `nextval`); `ALTER SEQUENCE …\n"
        "        RESTART WITH` takes a literal and excludes `nextval` for the transaction. Run it (dry-run,\n"
        "        then `--apply`) as step 0.5 above — the restore and the sequence floor are ONE action, not\n"
        "        a check-then-repair sequence.\n"
        "    (e) ``python -m kyc_tool.ops.repair_outbox_sequence`` is the SEPARATE DRAINED action for the\n"
        "        ONLY case the restore does not cover: a divergent sequence high-water with NO row to\n"
        "        restore (nothing missing, the counter itself is wrong). Same maintenance-stop\n"
        "        preconditions and owner privilege; pass `--floor` with the id when an id above max must stay"
        " cleared.\n"
        "        It is never a prerequisite the restore waits on.\n"
        "    (f) Only then rerun 0.4 (it must be clean — it also proves existence/1:1 of every mapping).\n"
        "\n"
        "**Cutover (only after 0.4 is green):**\n"
        "1. Pause submission, edge-block the composer, disable autoscaling/restarts.\n"
        "2. Hard-stop API, pipeline, outbox, `dev_worker` (queue AND outbox), retention, and every writer;\n"
        "   attest zero at the orchestrator.\n"
        "3. Run the shipped ``python -m kyc_tool.ops.requeue_interrupted_jobs``. NO outbox reset here — the\n"
        "   pre-013 schema has no claim columns; an interrupted old claim simply waits until its already-\n"
        "   recorded `next_attempt_at`. Preserve every pending row's `next_attempt_at`.\n"
        "4. Run ``python -m alembic -c alembic.ini upgrade head`` (the chain `013`→`014`→…→`022`→`023`) — the"
        " deployment image runs its exact\n"
        "   equivalent. This repeats the §0 parity preflights under the zero-writer boundary and is the\n"
        "   authoritative fail-closed check (the pre-window diagnostic is an early detector, not a substitute"
        ").\n"
        "   `017` additionally machine-checks the drain: it refuses with `MIGRATION_017_PREFLIGHT_LIVE_CLAIMS"
        "`\n"
        "   while any live (unexpired) outbox claim exists — leases must expire or be reset first.\n"
        "5. Start API only, probe `/readyz`, then start + attest the fenced workers. No mutating prod smoke."
        "\n"
        "6. RESUME (forward completion): re-enable retention, autoscaling/restarts, and submissions, and\n"
        "   remove the composer edge block. The window is NOT closed until all five paused controls\n"
        "   (retention, autoscaling, restarts, submissions, composer edge block) are restored or removed.\n"
        "\n"
        "**Rollback — a two-branch maintenance state machine (as drained as the forward cutover). BOTH branch"
        "es\n"
        "end in a full resume — never leave the system stopped or retention frozen:**\n"
        "R1. Pause submissions, edge-block the composer, disable autoscaling/restarts.\n"
        "R2. Hard-stop and orchestrator-attest zero API, pipeline, outbox, `dev_worker`, retention, every wri"
        "ter.\n"
        "R3. While 013 still exists, run ``python -m kyc_tool.ops.reset_interrupted_outbox_claims`` (post-013"
        "-only;\n"
        "    clears complete claim tuples, preserves `next_attempt_at`, atomically read-back-asserts zero) an"
        "d\n"
        "    verify zero claim tuples.\n"
        "R4. **With `018` or anything above it installed there is no schema-downgrade path**: `018` through\n"
        "    `022` refuse unconditionally — a walk from the head prints\n"
        "    `MIGRATION_022_DOWNGRADE_REFUSED_FORWARD_ONLY` (`023`'s downgrade is a validation-only\n"
        "    no-op the walk passes through first; the whole command is ONE transaction, so on refusal\n"
        "    even that step rolls back and the schema does not move) — because walking below them would resto"
        "re\n"
        "    search-path-vulnerable authority functions, so rollback goes straight to R5 (image-only on\n"
        "    the schema already installed). The walk below is the HISTORICAL path, reachable only on a\n"
        "    schema that never reached `018`: run ``python -m alembic -c alembic.ini downgrade 012`` (the rev"
        "ision is a\n"
        "    REQUIRED positional argument — a bare `alembic` downgrade invocation without it exits with a usa"
        "ge error\n"
        "    mid-outage). That walk is `017 → 016 → 015 → 014 → 013 → 012`, and EACH revision preflights\n"
        "    under\n"
        "    `LOCK TABLE ... ACCESS EXCLUSIVE` (child-first from `015` on; `017` first takes the shared\n"
        "    maintenance/writer advisory fence EXCLUSIVE, so it queues behind live witness writers instead\n"
        "    of reasoning about their lock order). Sentinels in execution order:\n"
        "    - `017` refuses — `MIGRATION_017_DOWNGRADE_REFUSED_WITNESS_IN_USE` — when ANY attempt row,\n"
        "      terminal wire digest, or `attempt_v1` decision callback exists. NEGATIVE evidence counts:\n"
        "      an attempt-regime row with no attempt is the durable proof nothing was staged.\n"
        "    - `016` refuses — `MIGRATION_016_DOWNGRADE_REFUSED_WITNESS_IN_USE` — same rule one revision\n"
        "      down (defense in depth below `017`), including the `attempt_v1` negative-evidence case.\n"
        "    - `015` refuses — `MIGRATION_015_DOWNGRADE_REFUSED_WITNESS_IN_USE` — on any attempt row or\n"
        "      terminal digest (child-first lock order; cannot deadlock a live writer).\n"
        "    - `014` refuses — `MIGRATION_014_DOWNGRADE_REFUSED_WITNESS_IN_USE` — same witness rule.\n"
        "    - `013` refuses on a `superseded` row, a surviving terminal digest\n"
        "      (`MIGRATION_013_DOWNGRADE_REFUSED_WITNESS_IN_USE`), or the attempt table under a bare `013`\n"
        "      stamp (`MIGRATION_013_DOWNGRADE_REFUSED_AMENDED_HISTORY`).\n"
        "R5. ROLLBACK OUTCOME A — downgrade REFUSED (any sentinel above): the DB stays on the\n"
        "    witness-authority schema, so KEEP or redeploy the reviewed **`023`-COMPATIBLE image** digest —\n"
        "    an older publisher lacks the receipt/terminal contract and MUST NOT run against preserved\n"
        "    evidence; PROHIBIT the pre-7b image outright. Rollback after first witness use is a\n"
        "    FLAG/IMAGE rollback on the compatible schema, never a schema downgrade. A pre-7b image is\n"
        "    permitted ONLY after the entire walk reaches `012` (outcome B). Verify `/readyz`, start + attest"
        " its fenced workers, then\n"
        "    re-enable retention, autoscaling/restarts, and submissions and remove the composer edge block —"
        "\n"
        "    OR remain in a DELIBERATELY DECLARED maintenance incident while the forward fix is applied. Do\n"
        "    not end stopped.\n"
        "R6. ROLLBACK OUTCOME B — downgrade SUCCEEDED: deploy the recorded prior-image digest; start API, pro"
        "be\n"
        "    `/readyz`, then start + attest its workers; attest image digest + running processes; then re-ena"
        "ble\n"
        "    retention, autoscaling/restarts, and submissions and remove the composer edge block. Redeploying"
        "\n"
        "    the pre-7b image BEFORE 013 is applied is also safe.\n"
        "",
        commands=(
            Command(('sha256sum', '<file.json>')),
            Command(('python', '-m', 'kyc_tool.ops.repair_outbox_sequence')),
            Command(('python', '-m', 'kyc_tool.ops.requeue_interrupted_jobs')),
            Command(('python', '-m', 'alembic', '-c', 'alembic.ini', 'upgrade', 'head')),
            Command(('python', '-m', 'kyc_tool.ops.reset_interrupted_outbox_claims')),
            Command(('python', '-m', 'alembic', '-c', 'alembic.ini', 'downgrade', '012')),
        ),
    ),
)
